package com.queuesense;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import java.nio.file.Files;
import java.nio.file.Paths;

@RestController
@CrossOrigin(origins = "*") // Allows React to fetch data from this API
public class QueueController {

    @GetMapping("/api/queue-status")
    public String getQueueStatus() {
        try {
            // Read the JSON file generated by our Python Data Analysis script
            String jsonContent = new String(Files.readAllBytes(Paths.get("queue_prediction.json")));
            return jsonContent;
        } catch (Exception e) {
            // Fallback in case Python hasn't run yet
            return "{\"currentlyServing\": 0, \"yourTicket\": 0, \"peopleAhead\": 0, \"estimatedWaitMins\": 0, \"historicalPace\": \"Pending AI Analysis\", \"safeToLeave\": false}";
        }
    }
}
